default_job = "clippy-fw"

[jobs]

[jobs.test]
command = ["just", "test"]
need_stdout = false

[jobs.check-drv]
command = ["just", "check-drv"]
need_stdout = false

[jobs.check-fw]
command = ["just", "check-fw"]
need_stdout = false

[jobs.check-lib]
command = ["just", "check-lib"]
need_stdout = false

[jobs.clippy-drv]
command = ["just", "clippy-drv"]
need_stdout = false

[jobs.clippy-fw]
command = ["just", "clippy-fw"]
need_stdout = false

[jobs.clippy-lib]
command = ["just", "clippy-lib"]
need_stdout = false

[keybindings]
t = "job:check-drv"
s = "job:check-fw"
r = "job:check-lib"
n = "job:test"
shift-t = "job:clippy-drv"
shift-s = "job:clippy-fw"
shift-r = "job:clippy-lib"
