default_job = "clippy-esp32"

[jobs]

[jobs.test]
command = ["just", "test"]
need_stdout = false

[jobs.check-drv]
command = ["just", "check-drv"]
need_stdout = false

[jobs.check-stm32]
command = ["just", "check-stm32"]
need_stdout = false

[jobs.check-esp32]
command = ["just", "check-esp32"]
need_stdout = false

[jobs.check-lib]
command = ["just", "check-lib"]
need_stdout = false

[jobs.clippy-drv]
command = ["just", "clippy-drv"]
need_stdout = false

[jobs.clippy-stm32]
command = ["just", "clippy-stm32"]
need_stdout = false

[jobs.clippy-esp32]
command = ["just", "clippy-esp32"]
need_stdout = false

[jobs.clippy-lib]
command = ["just", "clippy-lib"]
need_stdout = false

[keybindings]
t = "job:check-drv"
s = "job:check-stm32"
r = "job:check-esp32"
n = "job:check-lib"
c = "job:test"
shift-t = "job:clippy-drv"
shift-s = "job:clippy-stm32"
shift-r = "job:clippy-esp32"
shift-n = "job:clippy-lib"
